---

- name: Setup up script
  when: openvpn_bridge | bool
  template:
    src: bridge/up.sh.j2
    dest: "{{ openvpn_scripts_dir }}/up.sh"
    mode: o+x

- name: Setup down script
  template:
    src: bridge/down.sh.j2
    dest: "{{ openvpn_scripts_dir }}/down.sh"
    mode: o+x
  when: openvpn_bridge | bool

- name: Setup bridge
  template:
    src: bridge/bridge-interface.rh.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-br-{{ openvpn_dev }}"
  when: openvpn_bridge | bool
  notify: restart networking redhat

- name: Remove interface configuration for "{{ openvpn_dev }}"
  file:
    path: "/etc/sysconfig/network-scripts/ifcfg-br-{{ openvpn_dev }}"
    state: absent
  when: not openvpn_bridge | bool
